Repository sagar-jadhav/go-examples, pull requests merged in 2019-10, with the labels that each got.

#12 Update map.go
  src/map.go
Labels: good first issue, hacktoberfest

#13 Update recursion.go
  src/recursion.go
Labels: good first issue, hacktoberfest

#11 added example link to README.md
  README.md
  src/test/power.go
  src/test/power_test.go
Labels: good first issue, hacktoberfest

#25 Update readme
  README.md
Labels: good first issue, hacktoberfest

#38 Fix typo in println fn call
  src/struct.go
Labels: bug, good first issue

#39 Creating document for Hello World Program
  README.md
  docs/hello-world.md
Labels: documentation

#41 Add code of conduct file for the project
  CODE_OF_CONDUCT.md
Labels: documentation

#20 Reformat code and fix error of struct example
  src/struct.go
Labels: bug, hacktoberfest

#24 Fix bug in interface example
  src/interfaces.go
Labels: bug, hacktoberfest

#22 Add manipulation function to pointer example
  src/pointer.go
Labels: enhancement, hacktoberfest

#82 Adding concurrency example
  README.md
  src/concurrency.go
Labels: enhancement

#75 Added documentation of for loop in go
  README.md
  for-loop.md
Labels: documentation, good first issue, hacktoberfest

#34 Add PR template on project
  README.md
  pull_request_template.md
Labels: documentation, enhancement, hacktoberfest

#79 [Issue44] Added readme for Closure
  README.md
  closure.md
Labels: documentation, good first issue, hacktoberfest

#36 Implement stack ADT
  README.md
  src/stack.go
Labels: enhancement, hacktoberfest

#35 Add HTTP server example
  src/http_srv.go
Labels: enhancement, hacktoberfest

#74 adding simple-calculator doc
  README.md
  simple-calculator.md
Labels: documentation, hacktoberfest

#84 Add documentation for http_srv example
  README.md
  http_srv.md
Labels: documentation, enhancement, hacktoberfest

#87 Issue #72: Go Fmt Verbs
  format-verbs.md
  src/format-verbs.go
Labels: enhancement

#33 add comparison operators example
  README.md
  src/comparison-operators.go
Labels: enhancement
